const seedColors = [
  {
    paletteName: "Material UI Colors",
    id: "material-ui-colors",
    emoji: "",
    colors: [
      { name: "beekeeper", color: "#f6e58d" },
      { name: "turbo", color: "#f9ca24" },
      { name: "middle blue", color: "#7ed6df" },
      { name: "greenland green", color: "#22a6b3" },
      { name: "spiced nectarine", color: "#ffbe76" },
      { name: "quince jelly", color: "#f0932b" },
      { name: "heliotrope", color: "#e056fd" },
      { name: "steel pink", color: "#be2edd" },
      { name: "pink glamour", color: "#ff7979" },
      { name: "carmine pink", color: "#eb4d4b" },
      { name: "exodus fruit", color: "#686de0" },
      { name: "burgle", color: "#4834d4" },
      { name: "june bud", color: "#badc58" },
      { name: "pure apple", color: "#6ab04c" },
      { name: "deep amaru", color: "#30336b" },
      { name: "deep cove", color: "#130f40" },
      { name: "coastal breeze", color: "#dff9fb" },
      { name: "hint of ice pack", color: "#c7ecee" },
      { name: "soaring eagle", color: "#95afc0" },
      { name: "wizard grey", color: "#535c68" },
    ],
  },
  {
    paletteName: "American Palette",
    id: "americano-paletot",
    emoji: "",
    colors: [
      { name: "beekeeper", color: "#f6e58d" },
      { name: "turbo", color: "#f9ca24" },
      { name: "middle blue", color: "#7ed6df" },
      { name: "greenland green", color: "#22a6b3" },
      { name: "spiced nectarine", color: "#ffbe76" },
      { name: "quince jelly", color: "#f0932b" },
      { name: "heliotrope", color: "#e056fd" },
      { name: "steel pink", color: "#be2edd" },
      { name: "pink glamour", color: "#ff7979" },
      { name: "carmine pink", color: "#eb4d4b" },
      { name: "exodus fruit", color: "#686de0" },
      { name: "burgle", color: "#4834d4" },
      { name: "june bud", color: "#badc58" },
      { name: "pure apple", color: "#6ab04c" },
      { name: "deep amaru", color: "#30336b" },
      { name: "deep cove", color: "#130f40" },
      { name: "coastal breeze", color: "#dff9fb" },
      { name: "hint of ice pack", color: "#c7ecee" },
      { name: "soaring eagle", color: "#95afc0" },
      { name: "wizard grey", color: "#535c68" },
    ],
  },
  {
    paletteName: "Aussie Palette",
    id: "aussie-paletot",
    emoji: "",
    colors: [
      { name: "beekeeper", color: "#f6e58d" },
      { name: "turbo", color: "#f9ca24" },
      { name: "middle blue", color: "#7ed6df" },
      { name: "greenland green", color: "#22a6b3" },
      { name: "spiced nectarine", color: "#ffbe76" },
      { name: "quince jelly", color: "#f0932b" },
      { name: "heliotrope", color: "#e056fd" },
      { name: "steel pink", color: "#be2edd" },
      { name: "pink glamour", color: "#ff7979" },
      { name: "carmine pink", color: "#eb4d4b" },
      { name: "exodus fruit", color: "#686de0" },
      { name: "burgle", color: "#4834d4" },
      { name: "june bud", color: "#badc58" },
      { name: "pure apple", color: "#6ab04c" },
      { name: "deep amaru", color: "#30336b" },
      { name: "deep cove", color: "#130f40" },
      { name: "coastal breeze", color: "#dff9fb" },
      { name: "hint of ice pack", color: "#c7ecee" },
      { name: "soaring eagle", color: "#95afc0" },
      { name: "wizard grey", color: "#535c68" },
    ],
  },
  {
    paletteName: "Canadian Palette",
    id: "canadian-ui-colors",
    emoji: "",
    colors: [
      { name: "beekeeper", color: "#f6e58d" },
      { name: "turbo", color: "#f9ca24" },
      { name: "middle blue", color: "#7ed6df" },
      { name: "greenland green", color: "#22a6b3" },
      { name: "spiced nectarine", color: "#ffbe76" },
      { name: "quince jelly", color: "#f0932b" },
      { name: "heliotrope", color: "#e056fd" },
      { name: "steel pink", color: "#be2edd" },
      { name: "pink glamour", color: "#ff7979" },
      { name: "carmine pink", color: "#eb4d4b" },
      { name: "exodus fruit", color: "#686de0" },
      { name: "burgle", color: "#4834d4" },
      { name: "june bud", color: "#badc58" },
      { name: "pure apple", color: "#6ab04c" },
      { name: "deep amaru", color: "#30336b" },
      { name: "deep cove", color: "#130f40" },
      { name: "coastal breeze", color: "#dff9fb" },
      { name: "hint of ice pack", color: "#c7ecee" },
      { name: "soaring eagle", color: "#95afc0" },
      { name: "wizard grey", color: "#535c68" },
    ],
  },
  {
    paletteName: "French Palette",
    id: "french-ui-colors",
    emoji: "",
    colors: [
      { name: "beekeeper", color: "#f6e58d" },
      { name: "turbo", color: "#f9ca24" },
      { name: "middle blue", color: "#7ed6df" },
      { name: "greenland green", color: "#22a6b3" },
      { name: "spiced nectarine", color: "#ffbe76" },
      { name: "quince jelly", color: "#f0932b" },
      { name: "heliotrope", color: "#e056fd" },
      { name: "steel pink", color: "#be2edd" },
      { name: "pink glamour", color: "#ff7979" },
      { name: "carmine pink", color: "#eb4d4b" },
      { name: "exodus fruit", color: "#686de0" },
      { name: "burgle", color: "#4834d4" },
      { name: "june bud", color: "#badc58" },
      { name: "pure apple", color: "#6ab04c" },
      { name: "deep amaru", color: "#30336b" },
      { name: "deep cove", color: "#130f40" },
      { name: "coastal breeze", color: "#dff9fb" },
      { name: "hint of ice pack", color: "#c7ecee" },
      { name: "soaring eagle", color: "#95afc0" },
      { name: "wizard grey", color: "#535c68" },
    ],
  },
  {
    paletteName: "Chinese Palette",
    id: "chinese-ui-colors",
    emoji: "",
    colors: [
      { name: "beekeeper", color: "#f6e58d" },
      { name: "turbo", color: "#f9ca24" },
      { name: "middle blue", color: "#7ed6df" },
      { name: "greenland green", color: "#22a6b3" },
      { name: "spiced nectarine", color: "#ffbe76" },
      { name: "quince jelly", color: "#f0932b" },
      { name: "heliotrope", color: "#e056fd" },
      { name: "steel pink", color: "#be2edd" },
      { name: "pink glamour", color: "#ff7979" },
      { name: "carmine pink", color: "#eb4d4b" },
      { name: "exodus fruit", color: "#686de0" },
      { name: "burgle", color: "#4834d4" },
      { name: "june bud", color: "#badc58" },
      { name: "pure apple", color: "#6ab04c" },
      { name: "deep amaru", color: "#30336b" },
      { name: "deep cove", color: "#130f40" },
      { name: "coastal breeze", color: "#dff9fb" },
      { name: "hint of ice pack", color: "#c7ecee" },
      { name: "soaring eagle", color: "#95afc0" },
      { name: "wizard grey", color: "#535c68" },
    ],
  },
  {
    paletteName: "Dutch UI Colors",
    id: "dutch-ui-colors",
    emoji: "",
    colors: [
      { name: "beekeeper", color: "#f6e58d" },
      { name: "turbo", color: "#f9ca24" },
      { name: "middle blue", color: "#7ed6df" },
      { name: "greenland green", color: "#22a6b3" },
      { name: "spiced nectarine", color: "#ffbe76" },
      { name: "quince jelly", color: "#f0932b" },
      { name: "heliotrope", color: "#e056fd" },
      { name: "steel pink", color: "#be2edd" },
      { name: "pink glamour", color: "#ff7979" },
      { name: "carmine pink", color: "#eb4d4b" },
      { name: "exodus fruit", color: "#686de0" },
      { name: "burgle", color: "#4834d4" },
      { name: "june bud", color: "#badc58" },
      { name: "pure apple", color: "#6ab04c" },
      { name: "deep amaru", color: "#30336b" },
      { name: "deep cove", color: "#130f40" },
      { name: "coastal breeze", color: "#dff9fb" },
      { name: "hint of ice pack", color: "#c7ecee" },
      { name: "soaring eagle", color: "#95afc0" },
      { name: "wizard grey", color: "#535c68" },
    ],
  },
];

export default seedColors;
